"""empty message

Revision ID: db3c6287bbb3
Revises: None
Create Date: 2016-04-26 17:29:14.513000

"""

# revision identifiers, used by Alembic.
revision = 'db3c6287bbb3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
